### ISSUE TITLE
Not installable on Xenial

### ISSUE THREAD

**Issue by Vistaus** [ruditimmermans/Logviewer#6]
Hi, I tried to install the app on Xenial (Xiaomi Redmi 9), but nothing happens when I press the install button in OpenStore. Other apps install just fine from the OpenStore. Could you please look into this?

**Comment by maciek134** [comment]
Not sure what I can do, I don't even upload the app to the store because it needs manual review - you might want to make an issue on https://gitlab.com/theopenstore instead. In the meantime, try downloading the click from the previous versions page: https://open-store.io/app/logviewer.ruditimmer/versions

**Comment by Vistaus** [comment]
“Not sure what I can do, I don't even upload the app to the store because it needs manual review”

You're listed there as the uploader and the support URL points towards here, so it seems logical that I ask for help here.

I'll try an older version, thanks.

**Comment by maciek134** [comment]
The support URL is for the app, not the store and this is clearly an issue with the store itself, which is why I pointed you to it's issue tracker.
